# Site settings
title: devcolton's portfolio
description: PORTFOLIO
baseurl: "/devcolton.github.io" # the subpath of your site

# User settings
username: devcolton
user_description: I love coding
user_title: Web Developer
email: devcoltonkr@gmail.com
github_username:  github.com/devcolton

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
